### PR TITLE
Upgrade generator jhipster 6.9.0 jhipster vuejs 1.8.0

### PR DESCRIPTION
**Pull request by pascalgrimaud**

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@nassimerrahoui @adilabed : I upgrade to latest generator-jhipster and jhipster-vuejs
But I encounter a problem with Swagger.
I don't have time to investigate but I think it comes from the blueprint

**Comment by nassimerrahoui** [comment]
@pascalgrimaud : Ok, we will investigate on this problem

**Comment by pascalgrimaud** [comment]
so cool that you know how to push to my branch @adilabed :)

**Comment by pascalgrimaud** [comment]
I'm merging this to avoid conflict with next PR

**Pull request merged**
