### PR TITLE
Upgrade to jhipster 7.3.1

### PR DESCRIPTION
**Pull request by nassimerrahoui**
#174

### CODE REVIEW

**Comment by nassimerrahoui** [comment]
error-front

I have this error when I try to launch the frontend with `npm start`

Also, I launched the backend with `./mvnw -Dspring.profiles.active=static,dev`

For the moment, I can't figured out what exactly happen. Maybe i'is related to webpack.

**Comment by pascalgrimaud** [comment]
@nassimerrahoui : try to launch:
- delete node_modules and package-lock.json
- launch npm install
- npm run webapp:build
- then, start your app

Yes, the workflow is bad... But it's how "JHipster" works today...

**Comment by pascalgrimaud** [comment]
I'm having a very quick look here:
- checkout v7.3.1 branch in generator-jhipster project
- launch jhipster

I don't know how you upgraded this application, but there are a lot of missing code in front part, which is in v7.3.1 and not in this branch. That can explain your problem
Did you use jhipster upgrade ?

**Comment by nassimerrahoui** [comment]
> I'm having a very quick look here:
> 
> * checkout v7.3.1 branch in generator-jhipster project
> * launch jhipster
> 
> I don't know how you upgraded this application, but there are a lot of missing code in front part, which is in v7.3.1 and not in this branch. That can explain your problem Did you use jhipster upgrade ?

@pascalgrimaud I tried to upgrade manually with this:
`checkout v7.3.1 branch in generator-jhipster project`
`launch jhipster`

**Comment by nassimerrahoui** [comment]
I will try to re-upgrade manually

**Comment by nassimerrahoui** [comment]
Closing this PR to make another one or to let someone take the issue.

**Pull request closed without merging**
