### PR TITLE
Feature/21 loggers management

### LINKED ISSUE #21: Feature: Logs management
Similar to http://localhost:1337/admin/logs

We should be able to change the logs of other applications

### PR DESCRIPTION
**Pull request by nassimerrahoui**
Fix #21

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
Globally, I think the refresh should not be in the route selector.
- Instances page: route selector + refresh
- Metrics: route selector + refresh
- Health: route selector + refresh
- Configuration: route selector
- Logs: route selector
- API: route selector (managed by Swagger)

So you should extract the refresh from the route selector vue, and use it separately

**Comment by nassimerrahoui** [comment]
> Globally, I think the refresh should not be in the route selector.
> 
> * Instances page: route selector + refresh
> * Metrics: route selector + refresh
> * Health: route selector + refresh
> * Configuration: route selector
> * Logs: route selector
> * API: route selector (managed by Swagger)
> 
> So you should extract the refresh from the route selector vue, and use it separately

Yes, we can call these two components seperately so there are less dependent each other

**Comment by nassimerrahoui** [comment]
Bounty claimed : https://opencollective.com/generator-jhipster/expenses/18598

**Comment by pascalgrimaud** [comment]
@nassimerrahoui : approved

**Pull request merged**
